-- Generated by TripAdvisor Scraper
-- Date: 2026-01-16T10:25:26.739298

-- DESTINATIONS
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Maldives', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Suisse', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Japon', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Kenya', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Grèce', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Indonésie', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'USA', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Maroc', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'France', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Espagne', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'République Tchèque', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);
INSERT INTO destinations (name, country, city, description, image_url, tags, average_rating)
VALUES ('Unknown', 'Italie', '', 'Découvrez Unknown', '', ARRAY['travel'], 4.0);

-- PACKAGES
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Maldives", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Suisse", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Japon", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Kenya", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Grèce", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Indonésie", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers USA", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Maroc", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers France", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Espagne", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers République Tchèque", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';
INSERT INTO packages (destination_id, name, description, duration_days, price_per_person, max_persons, includes, images, is_active, available_from, available_to)
SELECT d.id, 'Unknown - Découverte', 'Découvrez Unknown. Découvrez Unknown', 6, 999.0, 4, '{"transport": "Vol A/R vers Italie", "hotel": "Hôtel 3*", "meals": "Petit-déjeuner inclus", "activities": ["Visite libre"], "transfers": "Transferts aéroport"}'::jsonb, ARRAY[''], true, '2024-01-01', '2024-12-31'
FROM destinations d WHERE d.name = 'Unknown';